TagFamily : tag16h5
ImagePath : tag_image/
ImageCount : 30
GenTags : [0, 1, 11, 12, 13, 14]
GenPath : gen_tags/

0 :
  File : tag16h5_0.png
  Size : 80
  Canvas : [200, 200]
  Extand_Dot :
    - [80, 80, 10]
    - [-80, -80, 10]
    - [-80, 80, 10]
    - [80, -80, 10]
  Pixpermm : 10
  Extrinsic :
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]

1 :
  File : tag16h5_1.png
  Size : 100
  Canvas : [600, 1000]
  Extand_Dot :
    - [200, 0, 20]
    - [0, 400, 40]
    - [-200, 0, 20]
    - [0, -400, 40]
  Pixpermm : 5
  Extrinsic :
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]

11 :
  File : tag16h5_11.png
  Size : 80
  Canvas : [200, 200]
  Extand_Dot :
    - [80, 80, 10]
    - [-80, -80, 10]
    - [-80, 80, 10]
    - [80, -80, 10]
  Pixpermm : 10
  Extrinsic :
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]
12 :
  File : tag16h5_12.png
  Size : 80
  Canvas : [200, 200]
  Extand_Dot :
    - [80, 80, 10]
    - [-80, -80, 10]
    - [-80, 80, 10]
    - [80, -80, 10]
  Pixpermm : 10
  Extrinsic :
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]
13 :
  File : tag16h5_13.png
  Size : 80
  Canvas : [200, 200]
  Extand_Dot :
    - [80, 80, 10]
    - [-80, -80, 10]
    - [-80, 80, 10]
    - [80, -80, 10]
  Pixpermm : 10
  Extrinsic :
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]
14 :
  File : tag16h5_14.png
  Size : 80
  Canvas : [200, 200]
  Extand_Dot :
    - [80, 80, 10]
    - [-80, -80, 10]
    - [-80, 80, 10]
    - [80, -80, 10]
  Pixpermm : 10
  Extrinsic :
    - [1, 0, 0, 0]
    - [0, 1, 0, 0]
    - [0, 0, 1, 0]
    - [0, 0, 0, 1]

ImageTopic : /camera/color/image_raw
ImageSize : [640, 480]
# ImageIntrinsic : [920.251953125, 0.0, 650.4122924804688, 0.0, 921.1195678710938, 355.5172424316406, 0.0, 0.0, 1.0]
# ImageDistrotion : [0.0, 0.0, 0.0, 0.0, 0.0] # k1 k2 p1 p2 k3
ImageIntrinsic : [562.215537, 0.000000, 313.578895, 0.000000, 562.296854, 239.057080, 0.000000, 0.000000, 1.000000]
ImageDistrotion : [0.102311, -0.262498, 0.001509, 0.001349, 0.000000] # k1 k2 p1 p2 k3
T_b_c :
  - [1, 0, 0, 0]
  - [0, 1, 0, 0]
  - [0, 0, 1, 0]
  - [0, 0, 0, 1]
PosePublishTopic : /Pose
